### ISSUE TITLE
FocusNode used after being disposed

### ISSUE THREAD

**Issue by barbalex** [flutter-form-builder-ecosystem/flutter_form_builder#812]
I am saving automatically when focus leaves the TextField:
```dart
Focus(
  onFocusChange: (hasFocus) async {
    if (!hasFocus && email.value != projectUser.userEmail) {
      try {
        projectUser.userEmail = email.value;
        await projectUser.save();
        emailError = null;
        setState(() {});
        }
      } catch (e) {
        emailError = e.toString();
        setState(() {});
      }
    }
  },
  child: FormBuilderTextField(
    name: 'email',
    decoration: InputDecoration(labelText: 'Email'),
    onChanged: (String? val) async {
      email.value = val ?? '';
    },
    validator: FormBuilderValidators.compose([
      (_) => emailError,
      FormBuilderValidators.required(context),
      FormBuilderValidators.email(context),
    ]),
    keyboardType: TextInputType.emailAddress,
    initialValue: projectUser.userEmail ?? '',
  ),
),
```

Unfortunately I keep getting this error:
```
E/flutter (20344): Once you have called dispose() on a FocusNode, it can no longer be used.
E/flutter (20344): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:117
E/flutter (20344): #1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:123
E/flutter (20344): #2      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:234
E/flutter (20344): #3      FocusNode._notify
package:flutter/…/widgets/focus_manager.dart:1052
E/flutter (20344): #4      FocusManager._applyFocusChange
package:flutter/…/widgets/focus_manager.dart:1800
E/flutter (20344): #5      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (20344): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (20344): #7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (20344): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (20344): #9      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (20344): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (20344): #11     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (20344): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (20344): #13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (20344): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

I am using flutter_form_builder in version 6.0.1.

Seems related to https://github.com/danvick/flutter_form_builder/pull/799. But that should be merged into version 6.0.1, I think.

**Comment by Draxent** [comment]
I have the same and I am using version 6.0.1

**Comment by rmControls** [comment]
I do have same error with my FormBuilderChoiceChip

**Comment by zsyphon** [comment]
Same issue here using FormBuilderTextField. @barbalex have you found a work around?

**Comment by barbalex** [comment]
@zsyphon I am not using form_builder any more.

**Comment by ravgeetdhillon** [comment]
@barbalex What package you are using then?

**Comment by huylethanh** [comment]
On version 6.1.0+1 the validation method cause the "Once you have called dispose() on a FocusNode". because if force to get the first invalid field.

**Comment by huylethanh** [comment]
> Same issue here using FormBuilderTextField. @barbalex have you found a work around? This is happening to me on the web currently.

Somehow, the app build with newest version. should force it to previous version. :(

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
