### ISSUE TITLE
🐛 Failed assertion in the scheduler callback (semantics.dart line 3023 pos 16)

### ISSUE THREAD

**Issue by FrazeColder** [flutter-form-builder-ecosystem/flutter_form_builder#978]
## Steps to Reproduce

I have created a repository in order to check where to problem is coming from. I found out, it is due to using a `RichText` widget with a `TextSpan` and a `TapGestureRecognizer` which opens a URL. However, this problem only occurs when all of the widgets I mentioned are wrapped up in a `FormBuilderCheckbox`. You can download my repo I have provided to reproduce the bug. Because I am not able to understand what the problem is and the exceptions means, I have created this ticket.

Can you please help me to solve this issue? I would like to be able to create a checkbox with text which also opens the browser to the terms and contions if you tap on them.

[Here you can download my repo.](https://github.com/FrazeColder/checkbox_debug)

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3023 pos 16: 'node.parent ==
null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:3023:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1098:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:502:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
The Flutter DevTools debugger and profiler on iPhone 13 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:60778/96VIfHcvjPI=/

```

```
Analyzing checkbox_debug...                                             
No issues found! (ran in 2.7s)
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale de-DE)
    • Flutter version 2.10.3 at /usr/local/Caskroom/flutter/2.10.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/jantrier/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 2042D746-4755-4638-8014-92CC2D15D4EE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by FrazeColder** [comment]
I do now know what's the problem here. Take a look at this: https://github.com/flutter/flutter/issues/99832#issuecomment-1066409788

There a flutter core developer describes the issue here. Is there any way we can add the possibility to add semantics in the CheckboxListTile in order to provide links within the text of CheckboxListTile?

Kind regards

**Comment by WilliamCunhaCardoso** [comment]
Were you able to solve it following the flutter team guide? https://github.com/flutter/flutter/issues/99832#issuecomment-1067567609

**Comment by FrazeColder** [comment]
Hi @WilliamCunhaCardoso 
sadly not... you are facing the same issue now?

**Comment by WilliamCunhaCardoso** [comment]
> Hi @WilliamCunhaCardoso sadly not... you are facing the same issue now?

Not yet. Unfortunately, I lack time to give a dedicated support, but I got a similar issue on camera. There were two gestures tap recognizer, one over another. Since I could not isolate them, I had to turn off one of them (the above one). I understand is not your case, you need both of them, right? I believe in such case,  Since you need both them clickable, and `Checkbox` component is whole clickable, I believe you may concatenate components, like a `Row` containing a `text` with a Checkbox, similar to what `ListTile` does.

Have you tried something like that? I am really sorry I cannot replicate your issue now.

**Comment by deandreamatias** [comment]
Hi @FrazeColder 
This still happens? Please if yes, add some steps to reproduce this bug
Thanks
